### ISSUE TITLE
Creates incorrect injections for class without class name

### ISSUE THREAD

**Issue by makepanic** [nikku/didi#17]
__Describe the Bug__

Hi,
I noticed that minified output sometimes inlines classes I pass to didi.
In this case, it generates an unexpected dependency called `class`.

__Steps to Reproduce__

1. parse annotations with a class without name.
```js
        expect(parseAnnotations(class{})).to.eql([ ]);
```
2. expect no dependencies
3. parseAnnotations in this example returns `[ "class" ]`

```
      AssertionError: expected [ 'class' ] to deeply equal []
      + expected - actual

      -[
      -  "class"
      -]
      +[]
```

__Expected Behavior__

Parsing this class should return an empty array or an array without `class`

__Environment__

- Host (Browser/Node version), if applicable: Node 16.17.0
- OS: linux
- Library version: 8.0.1

__Possible solution__

It seems like this happens because didi determines that a class is a class by checking if it [starts with `class `](https://github.com/nikku/didi/blob/master/lib/util.js#L1).
In the inlined case, the class can start with `class` without an extra space

Would it be ok to change the heuristic to check for `class ` or `class{`? I can create a PR with a test if that's ok.
I.e. a solution like the following would solve this issue:

```js
var CLASS_PATTERN = /^class[ {]/;` 
```

I've created https://github.com/nikku/didi/pull/18 which implements this solution

**Comment by nikku** [comment]
Thanks for opening this issue and for contributing a fix! :medal_sports:
