### ISSUE TITLE
Wrong Type Declaration for Injector#invoke

### ISSUE THREAD

**Issue by philippfromme** [nikku/didi#20]
__Describe the Bug__

The `context` and `locals` parameters of `Injector#invoke` are optional. The Type declaration doesn't reflect that:

```javascript
invoke<T>(func: (...args: unknown[]) => T, context: InjectionContext, locals: LocalsMap): T;
```

__Expected Behavior__

The declaration should be:

```javascript
invoke<T>(func: (...args: unknown[]) => T, context?: InjectionContext, locals?: LocalsMap): T;
```

**Comment by philippfromme** [comment]
The `func: (...args: unknown[]) => T` part doesn't seem to work either. It results in the following error:

```
Argument of type '(eventBus: EventBus) => any' is not assignable to parameter of type '(...args: unknown[]) => any'.
  Types of parameters 'eventBus' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'EventBus'.ts(2345)
```

That makes sense because I cannot use an `unknown` type.

**Comment by nikku** [comment]
Happy to take a contribution to fix this.

Likely makes sense to explicity [test this](https://github.com/nikku/didi/blob/master/test/integration/ts.spec.ts), too.

**Comment by philippfromme** [comment]
Okay, will file a PR. 😃

**Comment by philippfromme** [comment]
https://github.com/nikku/didi/pull/21 👀
