### ISSUE TITLE
Support for auto-annotate ES classes

### ISSUE THREAD

**Issue by nicojs** [nikku/didi#3]
I would expect this to work:

```js
var di = require('didi');

class Car {
    start() {
        console.log('success!');
    }
}

var module = {
    'car': ['type', Car],
};

var injector = new di.Injector([module]);
injector.invoke(['car', function (car) {
    car.start();
}]);
```

But what I get is this error:

```js
node_modules\didi\dist\didi.js:125
  return match[1] && match[1].split(',').map(function (arg) {
              ^

TypeError: Cannot read property '1' of null
    at parse (c:\z\github\nikku\tmp\node_modules\didi\dist\didi.js:125:15)
```

The problem seems to be with annotation.js, where the `toString` of the class is expected to include this regex:

` /^function\s*[^(]*\(\s*([^)]*)\)/m;`

But the toString is the class definition above and thus does not comply to the regex.

**Comment by nikku** [comment]
Feature implemented via https://github.com/nikku/didi/commit/99bccd5912e523f417c8599180972d68ff6eee16.

Give it a try.

**Comment by nicojs** [comment]
I've tried it, but it does not seem to work with didi@2.0.0.

```bash
\node_modules\didi\dist\index.cjs.js:55
  return match[1] && match[1].split(',').map(function(arg) {
              ^

TypeError: Cannot read property '1' of null
```

If I add `Car.$inject = [];`  it does work.

**Comment by nikku** [comment]
How does `fn.toString()` look like?

**Comment by nikku** [comment]
I got it. You're not specifying a constructor.

**Comment by nikku** [comment]
Fixed via https://github.com/nikku/didi/commit/72f780b3ec172b8303ad9f9b6fb49221973195d8.

**Comment by nicojs** [comment]
Great! Works like a charm
