### ISSUE TITLE
Support instantiating ES classes

### ISSUE THREAD

**Issue by nicojs** [nikku/didi#4]
I would expect this code example to work:

```js
var di = require('didi');

class Car {
    start() {
        console.log('success!');
    }
}

Car.$inject = [];

var module = {
    'car': ['type', Car],
};


var injector = new di.Injector([module]);
injector.invoke(['car', function (car) {
    car.start();
}]);
```

Instead i get this error:

```js
didi\dist\didi.js:316
    return fn.apply(context, dependencies);
              ^

TypeError: Class constructor Car cannot be invoked without 'new'
```

Which is pretty much self explanatory, apparently classes are not supported (yet). 

This is contradicted in the readme however:

> ` // if an object asks for 'car', the injector will call new Car(...) to produce it`
> `'car': ['type', Car],`

**Comment by nikku** [comment]
Feature implemented via https://github.com/nikku/didi/commit/99bccd5912e523f417c8599180972d68ff6eee16.

Give it a try.

**Comment by nicojs** [comment]
Thanks. This does work.
