### ISSUE TITLE
Installing this repository errors on git bash (Windows)

### ISSUE THREAD

**Issue by nicojs** [nikku/didi#5]
Running `npm i` in the repository errors on windows.

```bash
$ git clone git@github.com:nikku/didi.git
$ cd didi
$ npm i

> didi@2.0.1 prepare C:\z\utrechtjs\didi
> run-s bundle


> didi@2.0.1 bundle C:\z\utrechtjs\didi
> NODE_ENV=production rollup -c

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! didi@2.0.1 bundle: `NODE_ENV=production rollup -c`
```

Is the bundle step important to run on as "prepare" script? Can we maybe use [cross-env](https://www.npmjs.com/package/cross-env) to ensure it works on windows and linux?

**Comment by nikku** [comment]
I'm using Linux. If you'd like Windows to be supported for building the utility fix things with a PR.
